sudo: false
language: R
cache: packages
warnings_are_errors: false
install:
  - R -e 'if (system.file(package="ggplot2") == "") install.packages("ggplot2")'
  - R -e 'if (system.file(package="dplyr") == "") install.packages("dplyr")'
  - R -e 'if (system.file(package="tidyr") == "") install.packages("tidyr")'
env:
  - _R_CHECK_FORCE_SUGGESTS_=true
compiler:
  - gcc-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
before_install:
  - mkdir ~/.R
  - echo "CXX1X=g++-4.9" > ~/.R/Makevars
