sudo: false
language: R
cache: packages
r_packages: gifski
warnings_are_errors: false
r_packages:
  - rmarkdown
  - knitr
  - ggplot2
  - dplyr
  - tidyr
  - gifski
env:
  - _R_CHECK_FORCE_SUGGESTS_=true
compiler:
  - gcc-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - cargo
before_install:
  - mkdir ~/.R
  - echo "CXX1X=g++-4.9" > ~/.R/Makevars